### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by joeblew99** [yehohanan7/flux#2]
I like the simple offset mechanism.
The boltdb stores also, as it's seamless to get going.
I am glad a cqrs system like this is being setup and could help.

I don't get why the readme says it's all about not needing Kafka and the roadmap says it will be incorporated.

I would like to see this design allow running everything in a single application, whilst using drivers to easily flip the system into a multi server solution. This is becoming pretty doable. I am on mobile right now but can send you some links later.

**Comment by yehohanan7** [comment]
Hi @joeblew99 ,
That's right, the idea is not to use kafka/rabbitmq for simple applications, but what the road map talks about is as an option to push the events to external systems which may not be kafka. I will amend the read me accordingly.

**Comment by joeblew99** [comment]
Thanks for the additions.
This is fun to use , which is a good sign :)
Closing event horizon ( bad pun )...
