### ISSUE TITLE
Running client.http

### ISSUE THREAD

**Issue by marcalc** [yehohanan7/flux#4]
Hi, sorry for the newbie question, but which software do you use to run the requests specified in client.http file? I saw that there was a package for emacs, but I'm wondering if there is any mac/homebrew app that performs these tasks?

Thanks,
Marcos

**Comment by yehohanan7** [comment]
Hi @marcalc, the client.http file is created for using it in emacs with the help of this plugin - https://github.com/pashky/restclient.el
